apiVersion: v1
kind: Secret
metadata:
  name:
type: Opaque
data:
  MAILER_EMAIL:
  MAILER_PASSWORD:
  CLOUDINARY_API_KEY:
  CLOUDINARY_API_SECRET:
  CLOUDINARY_CLOUD_NAME:
  FIREBASE_AUTH_PROVIDER_CERT_URL:
  FIREBASE_AUTH_URI:
  FIREBASE_CLIENT_CERT_URL:
  FIREBASE_CLIENT_EMAIL:
  FIREBASE_CLIENT_ID:
  FIREBASE_PRIVATE_KEY:
  FIREBASE_PRIVATE_KEY_ID:
  FIREBASE_PROJECT_ID:
  FIREBASE_TOKEN_URI:
  FIREBASE_TYPE:
  FIREBASE_UNIVERSE_DOMAIN:
  MONGO_URI:
  NODE_ENV:
  PORT:
